image:
  imagePullPolicy: Always
  repository: ghcr.io/markus1978/code-server/code-server
  tag: latest

persistence:
  enabled: enabled

extraInitContainers: |
  - name: customization
    image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    imagePullPolicy: Always
    env:
      - name: SERVICE_URL
        value: https://open-vsx.org/vscode/gallery
      - name: ITEM_URL
        value: https://open-vsx.org/vscode/item
    command:
      - sh
      - -c
      - |
        code-server --install-extension ms-python.python
        code-server --install-extension charliermarsh.ruff
        code-server --install-extension catppuccin.catppuccin-vsc
        code-server --install-extension catppuccin.catppuccin-vsc-icons
        code-server --install-extension vscodevim.vim
        code-server --install-extension esbenp.prettier-vscode
        cp /config/data/User/settings.json /home/coder/.local/share/code-server/User/settings.json
        cp /config/data/User/keybindings.json /home/coder/.local/share/code-server/User/keybindings.json
        echo 'source /usr/share/bash-completion/completions/git' > /home/coder/.bashrc
        echo 'source /usr/share/bash-completion/completions/gh' >> /home/coder/.bashrc
    volumeMounts:
      - name: data
        mountPath: /home/coder